services:
  postgres:
    image: postgres
    container_name: postgres-medclinic
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart:
      always
    networks:
      - app-network

  app_service:
    build:
      context: ./backend/app_service
      dockerfile: Dockerfile
    container_name: app-service-medclinic
    depends_on:
      - postgres
    restart:
      always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./migrations:/migrations
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-medclinic
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro # Config file for nginx
      - ./frontend/frontend/dist/:/usr/share/nginx/html # All the react app files are here
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  postgres-data:
    driver: local
    name: postgres-data
