services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart:
      always
    networks:
      - app-network

  app_service:
    build:
      context: ./backend/app_service
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart:
      always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./migrations:/migrations
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  postgres-data:
    driver: local
    name: postgres-data
