services:
  app_service:
    build:
      context: ../../backend/app_service
      dockerfile: Dockerfile
    container_name: app-service-medclinic
    depends_on:
      - postgres
    restart:
      always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "8000"
    volumes:
      - ../../migrations:/migrations:ro
    networks:
      - app-network
