services:
  postgres:
    image: postgres
    container_name: postgres-medclinic
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart:
      always
    networks:
      - app-network
